version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [7f:e6:cb:d6:41:1a:02:57:94:cb:60:11:94:75:57:54]
      - run:
          name: Install dependencies
          command: |
          apk add --update ansible
      - run:
          name: Configure Server
          command: |
          ansible-playbook -i inventory.txt playbook.yml
